# 1. 项目唯一标识 (请替换为你在 SonarQube 网页上创建项目时的 Key)
sonar.projectKey=chessmanit023-sudo_minigame

# 2. 项目名称 (可以随意起，建议用英文)
sonar.projectName=minigame-Paoku

# 3. 源代码目录 (. 代表当前目录)
sonar.sources=.

# 4. 排除不需要扫描的文件夹 (Cocos Creator 项目必须排除这些，否则扫描极慢)
sonar.exclusions=library/**,temp/**,build/**,assets/**/*.fire,settings/**

# 5. 源码编码格式
sonar.sourceEncoding=UTF-8